-- 開発時に管理者として接続するユーザー
CREATE ROLE "devAdmin" WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	BYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'devAdmin';

-- 開発時にアプリケーションから接続するユーザー
CREATE ROLE "devApp" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	REPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'devApp';
